# Generated by Django 4.2.16 on 2024-11-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voca',
            name='was_memorized',
            field=models.BooleanField(default=False),
        ),
    ]
