# Generated by Django 4.2.16 on 2024-11-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='achievement_level',
            field=models.IntegerField(default=1),
        ),
    ]
